-- +migrate Up
CREATE TABLE songs (
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  artist VARCHAR(255) NOT NULL,
  album VARCHAR(255) NOT NULL,
  genre VARCHAR(255) NOT NULL,
  length INT(11) NOT NULL,
  url VARCHAR(255) NOT NULL,
  year INT(11) NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  PRIMARY KEY (id)
);